# Generated by Django 5.2 on 2025-05-11 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
